### PR TITLE
C4DF Version 11 - CP / CBP Beta v1

### PR DESCRIPTION
**Pull request by mwhiter**
C4DF Version 11 Beta v1

I wouldn't merge this until I get back from work tomorrow (about 7 EST) but this is the pull request that I believe is in stable enough condition for forking into Community Patch DLL.

I did not merge any files into EUI, I want some extra time before I do that, so for now, it's a NoEUI-only. I've also included my folder for the CP mod, but maybe you should take some time reviewing the package to ensure it's up to standards, otherwise I can make necessary edits.

### CODE REVIEW

**Comment by LoneGazebo** [comment]
Looks good. Merged manually, and I've done the EUI merge (there wasn't much to do). Should be good to go, and I put all of the C4DF changes in the (4) C4DF file for the Project package.

**Comment by mwhiter** [comment]
Okay great. I'd like to do a quick check just to make sure nothing is broken with the release package (the one you create) before it gets added to a beta. Should not take too long.

**Comment by LoneGazebo** [comment]
Sounds good. I'll put everything on github this evening. Probably not going to release the next beta until tomorrow anyways.

**Comment by mwhiter** [comment]
Were you able to fix the issue with VO screen not showing up? I noticed I don't have the civ5sln file for the Civ IV diplo in the repo in order to add the VO to the mod properties

**Comment by LoneGazebo** [comment]
Yeah, as all lua files are in the CBP-Compatibility file, I added it there. There's no 'button' for it in EUI, though, which we'll need to figure out (and make C4DF a custom vassal icon).

**Comment by mwhiter** [comment]
Thanks! And I'm not sure what icon it would use, but something like this, stylised for civ 5 would work. 

http://downloadicons.net/sites/default/files/castle-icon-88712.png

**Comment by LoneGazebo** [comment]
Yeah, that'd work.

G

**Comment by LoneGazebo** [comment]
Alright, everything's sync'd up (see the C4DF file on the master for your changes). LUA changes are in the EUI and no-EUI versions. If you get a button up for EUI, should be good to go.

**Comment by mwhiter** [comment]
I am no artist. I won't be able to make an icon that matches civ 5's art style. Maybe somebody more talented than I can do it? Can a placeholder be used for now (like an existing question mark icon?)

**Comment by LoneGazebo** [comment]
I've worked a button up for you! May not be perfect, but I'm pretty happy with it (no artist myself, but I'm not too bad with GIMP).


[VassalIcons.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/153001/VassalIcons.zip)

**Comment by LoneGazebo** [comment]
I also included the xcf icons for gimp if you want/need to edit them. I'm going to work on a rudimentary integration for EUI now.

**Comment by Iamblichos** [comment]
off topic question for you G, are you going to merge ilteroi's latest commits also into 2-29 beta?

**Comment by LoneGazebo** [comment]
Which? I've merged whatever he had posted as of yesterday.

**Comment by mwhiter** [comment]
Hey G could you provide an imgur link because I can't open dds on my phone and I'm anxious to see

**Comment by LoneGazebo** [comment]
dc45_vassaloverview

**Comment by LoneGazebo** [comment]
Here it is for EUI. The blue is the transparent background.

**Comment by mwhiter** [comment]
Beautiful!  Satisfies my requirements.

**Comment by LoneGazebo** [comment]
I'll post a pic once I get it to show in-game.

G

**Comment by Iamblichos** [comment]
@LoneGazebo, it says his branch is 86 commits ahead of master, figured you hadn't merged the hedgehog moves..

**Comment by LoneGazebo** [comment]
I merged it manually. 

FYI I found two small problems with my upload, so I'll be fixing those. Vassalage seems to be working properly, for what it is worth.

Having a hard time getting the button to show up properly in the game...

**Comment by Iamblichos** [comment]
@LoneGazebo Thanks, and sorry I forgot you did that. Just wanted to double check before I pull your changes into my branch.

**Comment by LoneGazebo** [comment]
Yeah, but wait a bit to merge, @Iamblichos.

**Comment by mwhiter** [comment]
Thinking about it now, it will make sense for me to include that vassal button next to the espionage overview because it is possible to have "pending" actions (like na unassigned spy) that needs a number shown (this action is # of vassals without tax values assigned)

**Comment by LoneGazebo** [comment]
The number itself requires, IIRC, a special button for every single integer value. We can, however, assign a tooltip to it, which should work. That, however, I leave to you. :)

**Comment by mwhiter** [comment]
Wait, are you kidding me right now? 0_0 that is not a label overlay in XML?

**Comment by LoneGazebo** [comment]
Not that I know of, no.

G

**Comment by mwhiter** [comment]
`-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
function DoUpdateEspionageButton()
	local iLocalPlayer = Game.GetActivePlayer();
	local pLocalPlayer = Players[iLocalPlayer];
	local iNumUnassignedSpies = pLocalPlayer:GetNumUnassignedSpies();
	
	local strToolTip = Locale.ConvertTextKey("TXT_KEY_EO_TITLE");
	
	if (iNumUnassignedSpies > 0) then
		strToolTip = strToolTip .. "[NEWLINE][NEWLINE]";
		strToolTip = strToolTip .. Locale.ConvertTextKey("TXT_KEY_EO_UNASSIGNED_SPIES_TT", iNumUnassignedSpies);
		Controls.UnassignedSpiesLabel:SetHide(false);
		Controls.UnassignedSpiesLabel:SetText(iNumUnassignedSpies);
	else
		Controls.UnassignedSpiesLabel:SetHide(true);
	end
	
	Controls.EspionageButton:SetToolTipString(strToolTip);
end
Events.SerialEventEspionageScreenDirty.Add(DoUpdateEspionageButton);`

Seems to me like it uses a label, which would make incredible sense.

**Comment by LoneGazebo** [comment]
Looks like it, yep. I'm thinking of notifications, not the diplo buttons.

**Comment by mwhiter** [comment]
Okay cool. I'm currently in the process of doing some last minute bugfixes (for example, the defensive pact bug), although there will be plenty of time to do that when the beta releases as well :)

**Comment by LoneGazebo** [comment]
Sounds good. I'm working on the EUI integration. So far so good, though the button doesn't seem to 'do' anything when clicked...

**Comment by mwhiter** [comment]
What code are you using to capture the event?

**Comment by LoneGazebo** [comment]
Edited DiploCorner.lua (so that the button only appears once vassalage is active): 

''-- C4DF
function OnVassalButton()
	Events.SerialEventGameMessagePopup{ 
		Type = ButtonPopupTypes.BUTTONPOPUP_MODDER_11,
	};
end
Controls.VassalButton:RegisterCallback(Mouse.eLClick, OnVassalButton);
--END''

**Comment by LoneGazebo** [comment]
It's asking for the option NO_VASSALAGE, so this is being captured, but it seems that 

```
if( ContextPtr:IsHidden() == false ) then
        			OnClose();
				else
```

ContextPtr is never being set to true...

**Comment by LoneGazebo** [comment]
Or rather, 'not hidden'

**Comment by mwhiter** [comment]
Don't worry about having it not shown until vassalage is active, it should always appear.

**Comment by mwhiter** [comment]
Only shouldn't appear if no vassalage game option is enabled

**Comment by LoneGazebo** [comment]
Well, the button itself is appearing fine, but clicking it does nothing. Not sure why. I'll upload my EUI in a moment so you can take a look.

**Comment by mwhiter** [comment]
okay that's fine. Do that.

Where are you gonna be storing the .dds file? Is that something source-controlled? Also do you have plans to add my custom CP-only C4DF to the repository?

**Comment by LoneGazebo** [comment]
It's in the EUI I'm about to upload. I made it, but it's for your mod, so it's yours as far as I'm concerned. 

I can add your C4DF copy if you'd like.

**Comment by mwhiter** [comment]
I need it for my base mod anyway

**Comment by mwhiter** [comment]
Can you also add it to the C4DF folder?

**Comment by LoneGazebo** [comment]
Alright, uploading now. Check the EUI compatibility files - all changes are marked C4DF (look at the changelist for the merge to see what I edited).

**Comment by LoneGazebo** [comment]
Button still doesn't work for me, but it is showing up properly, and it looks 'stock,' so that's good.

Man, I hate LUA!

**Comment by LoneGazebo** [comment]
You can find the art file in the EUI I just uploaded. Let me know if/when you've got the button working (and then upload the fix so I can push the beta out).

**Comment by mwhiter** [comment]
You and me both, and I'm the one who spent 2 weekends knocking out a new overview

**Comment by LoneGazebo** [comment]
The amount of loading/reloading is what kills me. I had that same ordeal with my corps/monopolies overview. Maddening! Let me know what you find out.

**Comment by mwhiter** [comment]
Have you tested the firetuner to ensure no runtime error?

**Comment by mwhiter** [comment]
The only thing I can think of (looking at the code) is that the VO does not actually exist. I've experienced this issue if for some reason my mod is not loaded. The DLL code works, but the front end stuff is missing.

Other than that, I don't see any glaring issues with the code unless there's a runtime error that is preventing the action from occurring. I recommend print statements.

**Comment by mwhiter** [comment]
when you can, move the .dds into CBP C4DF folder (I can't because I don't have the .civ5sln for the mod used in CBP). I'll investigate the icon issue further.

**Comment by LoneGazebo** [comment]
Does the VO need to be added as a UIAddin? Or is the VFS enough? I forget.

**Comment by mwhiter** [comment]
VFS is not enough. It does.

**Comment by LoneGazebo** [comment]
Ah, that's my misstep, then. I always forget about that. Sigh...

**Comment by mwhiter** [comment]
Hopefully solves the issue. I'm working on a last minute update to get the VO icon to appear in the diplocorner for the main mod.

You can just reuse my code for that. Should not take too long.

**Comment by LoneGazebo** [comment]
It's working now, yep. Only oddity is that it seems the window is being created twice when I click the button. Any ideas on that?

**Comment by mwhiter** [comment]
Not happening for me. Use my code. It's working as expected right now.

**Comment by mwhiter** [comment]
Known issues:

1. VO icon does not update until the start of your next turn
2. Capitulated vassals do not yet count for Domination victory (tooltip is incorrect). Will correct in a future Beta.

**Comment by LoneGazebo** [comment]
VO update issue - look at the EUI code I did (there's a 'on notification type' check that you can use). The code is in DiploCorner.lua.

G

**Comment by mwhiter** [comment]
won't really help in this case, because when you update vassal taxes no notification is sent.

it has to be a DLL dirty bit change, but I'll handle that case later.

**Comment by LoneGazebo** [comment]
Sounds good. Let me know when all your latest is merged and I'll merge it all for the beta.

**Comment by mwhiter** [comment]
okay it's push to my local.

One more thing: I used the regular and HL versions of the icons you sent me earlier. Don't forget to VFS true them for my C4DF solution!

**Comment by mwhiter** [comment]
I also forgot to push the DiploCorner lua and XML to Non-EUI

**Comment by mwhiter** [comment]
Okay it's pushed as well

**Comment by LoneGazebo** [comment]
Sounds good, will do. When you get a chance, send me your solution file for C4DF so I can make sure we're sync'd up on that front.

**Comment by mwhiter** [comment]
I have been developing with (1a) Community Patch - C4DF which should be included in my pushes. That is the CP-only. I have not been developing with the CBP C4DF, but as far as I know, the only thing  you'd have to do differently is remove every file except for VassalageOverview from the LUA folder.

**Comment by mwhiter** [comment]
((because I have no solution for C4DF CBP))

**Comment by LoneGazebo** [comment]
I was asking for the solution file for your (1a) file, as I can make sure the files match up in C4DF. No worries, though, I can handle it without.

**Comment by mwhiter** [comment]
https://github.com/mwhiter/Community-Patch-DLL/tree/master/(1a)%20Community%20Patch%20-%20C4DF%20Addon

**Comment by LoneGazebo** [comment]
Thanks!

**Comment by LoneGazebo** [comment]
Did you get the EUI version to stop appearing twice when you click the button? It's not a huge deal, but I also don't see why it is happening.

**Comment by mwhiter** [comment]
no i didn't test the EUI version only the CP version.

But that's an issue that can be ironed out in beta testing.

**Comment by mwhiter** [comment]
I will also be adding other things so the version that's being added now is not the complete version. It's feature complete, but not **polished**

**Comment by mwhiter** [comment]
i have a list of things that need to get done

**Comment by LoneGazebo** [comment]
Sounds good. I'll start the beta process later this evening. Should be up in a few hours.

**Comment by mwhiter** [comment]
Patch notes civfanatics forum code:

[spoiler]
[B]General[/B]
[LIST]
[*]Masters now receive a +33% tourism bonus against their vassals
[*]Vassals can no longer be considered for Choose Host or World Leader – but they still become host of the World Congress upon founding it.
[*]Death of a Vassal's unit inside his territory now counts for failed protect score
[*]Death of a Vassal's unit inside enemy territory no longer counts for failed protect score 
[*]Pillaged vassal territory now applies a small failed protect score
[*]Notifications related to Vassalage have received an upgrade to be more descriptive.
[*]Upon capitulation (forced vassalage as part of a peace treaty), the new vassal will reset negative diplomatic modifiers similar to civ resurrection. Voluntary vassals are not affected by this.
[*]You can declare war on your vassals, but other teams cannot declare war on your vassals. This provides two options of breaking vassalage: declaration of war, and peaceful liberation (see Vassal Liberation section).
[*]Extended range of failed protect score near vassal cities to 3 hexes away.
[*]Added a new Vassalage Overview – see the Vassalage Overview section
[*]Technology Trading has been moved to Scientific Theory
[/LIST]

[B]AI[/B]
[LIST]
[*]AI Vassals can denounce their masters – the weight is determined based on how well you've treated your vassal.
[*]AI Masters will never denounce their vassals
[*]Retooled AI evaluation on the following:
[LIST]
[*]Wants to capitulate
[*]Wants to become your voluntary vassal
[*]Wants to end vassalage with master
[*]Wants to accept human's bid to end vassalage
[/LIST]
[*]Now evaluate a few flavors (expansion, offense, military training defense, culture, wonder) when determining whether a vassal wants to become a voluntary vassal or not.
[LIST]
[*]For example: Ramesses is 22, Enrico is 10, Shaka is -34, Attila is -14
[*]Note to modders: if you delete those flavors, then the flavor mod difference for that flavor is 0
[/LIST]
[*]Common sense evaluation: If an AI is going for diplomatic victory, and the United Nations has started, then they will never accept voluntary vassalage and will attempt to leave vassalage immediately.
[/LIST]

[B]New Feature: Vassal Overview[/B]
[LIST]
[*]In an effect to provide a unified and easy to manage screen for all things related to Vassalage, I have created the Vassal Overview
[*]If you have vassals, you can select each one individually to receive more details about them
[*]The Vassal Overview  provides a concise description of the type of vassalage, how long the vassalage has lasted (and the turn it started) as well as helpful tooltips to provide more meaning to things that can be unclear to the player.
[*]On the left side of the Vassal Details box, you can see basic stats (similar to the top panel for your own civ) for your vassal. You can also see what tech they are researching, and how long
[*]On the right side of the Vassal Details box, you can set your vassal taxes and view details on how they view your vassalage and why they feel that way. You can also liberate your vassal (when applicable, see Vassal Liberation section)
[/LIST]

[B]New Feature: Vassal Taxes[/B]
[LIST]
[*]You can set vassal taxes on intervals of 5% (from 0%-25%).
[*]Vassal taxes are applied per vassal, but distributed evenly amongst teammates.
[*]Vassal taxes are calculated at the beginning of the vassal's turn and are a percentage of their gross (positive gold) income.
[*]The heavier you tax a vassal, the more they will hate you.
[*]AI teammates will never set taxes for human players.
[*]AI opponents will set taxes based on a number of factors, including how much they like you, and how both of your financial situations are.
[/LIST]

[B]New Feature: Vassal Liberation[/B]
[LIST]
[*]Masters can now liberate their vassals after a certain period of turns (50 turns on Standard). 
[*]Liberation of  vassals acts as a peaceful removal of vassalage, and grants a huge positive modifier for liberating a vassal
[*]You may liberate vassals when eligible through the new Vassalage Overview
[*]You may request independence from masters through the new Vassalage Overview
[*]AI masters will liberate you if they like you, and they do not deem you a threat to them
[*]This is not the same as resurrecting a player, so you will not receive a reset in negative diplomatic modifiers.
[/LIST]

[B]Bugfixes[/B]
[LIST]
[*]Fixed a bug where voluntary vassalage was not being correctly set
[*]Fixed a bug where you could call the LUA function DoBecomeVassal() with invalid civs (for example, could set a civ to be a vassal of itself)
[*]Reversed the function for canBecomeVassal() to be actually sane. This mostly affects modders:
[LIST]
[*]Team1.canBecomeVassal(Team2) now checks if Team1 can become Team2's vassal, was Team2 can become Team1's vassal
[/LIST]
[*]Added new function CanMakeVassal() which is simply the reverse of CanBecomeVassal()
[*]Fixed issue where DealAI did not send offers to revoke human vassals
[/LIST]

[B]UI[/B]
[LIST]
[*]Complete pass on tooltips on the Diplomacy Trade screen related to "Vassal State", "Capitulation", and "Liberation" in an effort to provide more clarity to the player
[/LIST]
[/spoiler]

Upcoming for the Beta:

[spoiler]
[LIST]
[*]Finish tooltips in Vassal Overview for human vassal (very incomplete atm)
[*]Verify that AI behavior is normal when AI is vassal of another AI
[*]New player help Foreign Advisor
[LIST]
[*]Vassalage enabled
[*]You are a vassal
[*]You have a vassal
[/LIST]
[*]New notifications:
[LIST]
[*]Liberation Possible
[*]Vassal can declare independence
[*]You can declare independence
[/LIST]
[*]New vassal treatment modifier: Your ideology is different than our preferred ideology (-50)
[*]Any additional discovered bug / crash fixes related to C4DF
[*]Tooltip pass
[*]Civilopedia pass
[/LIST]
[/spoiler]

**Comment by LoneGazebo** [comment]
Awesome! Will include.

**Pull request closed without merging**
