### PR TITLE
Ekeuhnick 14/04/19

### PR DESCRIPTION
**Pull request by HungryForFood**
## Trait_NonSpecialistFoodChange 
- Added Trait_NonSpecialistFoodChange (changes the food consumed by each non-specialist citizen).

### CODE REVIEW

**Comment by pineappledan** [comment]
Yaaaaaay!

**Comment by pineappledan** [comment]
So what do I need to change in the Inuit mod so that the trait still works?

**Comment by HungryForFood** [comment]
When I coded it in, there was a small possibility that the food discount might depend on terrain, so I didn't want to redo everything if that's the case.

Another small thing is that the debug database looks neater in SQLite Spy.

Does it make a big difference?

**Comment by LoneGazebo** [comment]
@HungryForFood,

Yes it takes up more memory to do it this way. 

G

**Pull request merged**
