### PR TITLE
Update autovariables

### PR DESCRIPTION
**Pull request by LoneGazebo**

### CODE REVIEW

**Comment by LoneGazebo** [comment]
@IanE9 I don't want to screw up your changes, mind resolving these conflicts, make sure I'm not messing up your work?

**Comment by IanE9** [comment]
I'll do so as soon as I can 👍

**Comment by LoneGazebo** [comment]
thanks, no rush. I'm going to start testing this now that 6-7 is out.

**Comment by IanE9** [comment]
I resolved the conflicts locally and added them to my serialization fork. The pull request I've made should bring it all up to date and include some changes I made yesterday.

**Pull request closed without merging**
