### PR TITLE
Fix CargoShipMod.sql

### PR DESCRIPTION
**Pull request by Iamblichos**

### CODE REVIEW

**Comment by Iamblichos** [comment]
Heh that baby must be napping.

**Comment by LoneGazebo** [comment]
Even better - she's all about the wife right now, which means daddy's free to write some sweet, sweet code! :dancer:

**Comment by Iamblichos** [comment]
I hear ya buddy, I have an 8 month old a four year old girls!

**Comment by LoneGazebo** [comment]
9 days and counting here. Loving it, but some code time is welcome. :)

**Comment by Iamblichos** [comment]
You getting any sleep?

**Comment by LoneGazebo** [comment]
Some. Sometimes. She's actually a really good baby. Barely fusses, mainly wants to eat and sleep.

**Comment by Iamblichos** [comment]
That's good. Both of mine had huge spit up issues. Took forever to fine the right forumula.

**Comment by Iamblichos** [comment]
Well I can already see I put the Update for the Language (about a 1/4 down the page) to append the Help text for Melee boats in the wrong place. Needs to be at the end. Not a big deal. Things you do in a hurry cutting and pasting.

**Comment by LoneGazebo** [comment]
Ah, no spit up or colic here (yet). Biggest issue is actually getting her to wake up at 4/8am for feedings. She loves sleep!

Re; text, I'm pushing a version shortly for you and @jfdaly to test for me. We'll test that, then I'll probably push an update tomorrow. I'd love to release modpacks at same time if we can.

**Pull request merged**
