### PR TITLE
TacticalMap updating and desyncs

### PR DESCRIPTION
**Pull request by davenye**
Tactical data is desyncing. I believe it is largely to do with the caching mechanism on the TacticalMap.

The TacticalMap is only updated at most once per turn due to existing caching logic. I suspect that the data is desyncing due to the cache being updated at different points on some clients. Unfortunately I haven't figured out the conditions in which the update points are different. Instead I have tried to minimise the potential to desync by forcing updates at specific points. I have also added the ability to invalidate the cache so that the cache is still rebuilt at a later point in the turn (as seems to be desired, otherwise there would not be a need to be lazy about the updates).

This change is very heavy handed but does appear to help prevent desyncs. It can be cleaned up and optimized but right now I just want to prevent desyncs and don't want to worry about something not being updated when it needed to be. With some more investigation I hope to confirm the root cause of the desyncing.

At any rate, it does look like they were being updated too early by CvPlayer::UpdateCityThreadCriteria. A comment in the TacticalMap class says that refreshing should be done after danger plots are updated in CvPlayer::doTurnPostDiplomacy - CvPlayer::UpdateCityThreatCriteria is called just before that.  This sounds like a bug that can be addressed in single player also.

I assume that it is desirable to have the TacticalMap refreshed during ai_unitUpdate, so I also implemented a means of invalidating the cache so that the map is updated then if need be...unless of course something else updates it beforehand.

This is just hanging together and could benefit from further thought but I am not familiar enough at the moment. Is it worth considering forcing an update in ai_unitMoves instead? Maybe just the invalidating is enough. Maybe just re-ordering UpdateCityThreatCriteria would be enough?

In addition to this, I am forcing an update of ALL tactical maps upon war or peace. This most likely overkill  but my testing was done using this and am reluctant to change right now. It could probably be just done for the involved teams in the make war/peace methods (like before or in better spots still, such as DoNowAtWarOrPeace or setAtWar). Existing code was asking the TacticalMap to refresh but this was unlikely to be effectual due to the once-per-turn limit imposed by the caching mechanism.

This change will need to see some refinement before committing to master, even if it is just some wrapping to make it MP only.

### CODE REVIEW

**Comment by LoneGazebo** [comment]
@ilteroi may be interested in this. I've long worried that the tactical AI was a problem part of desyncs, but it's interesting to see that theory tested.

**Comment by raphaell666** [comment]
God bless you @davenye. I will see if I can test these changes in the mp_bugfixes branch in my next game. If these help reduce desyncs I will be so happy I don't even know what I am going to do.

**Comment by davenye** [comment]
Unfortunately I have still seen it drift a little and the root cause is still there. I only recently tried this but in my limited testing it did seem to help and didn't seem to increase processing time much.

I am yet to really look into how the tactical map related stuff works at all. There is some code relating to the updating of danger plots that I don't understand the reasoning behind but I wonder if it is part of the problem. I do hope to find out more from @ilteroi in the future.

Thanks @raphaell666, that would be great. I will be building a modpack with the changes soon, after a bit of a test to try to find any possible merging errors/omissions.

**Comment by raphaell666** [comment]
Update: I tested the fixes in the mp_bugfixes branch, and although the game itself seemed to work perfectly fine, we still were having desyncs as usual, at least as far as I could tell. I really could not tell if there was an improvement or not regarding resyncs. We played a Large 2 player + 8 AI + 20 City-States game to "favor" desyncs, and quit around turn 120 because it was resyncing nearly every turn already. This might have been bad luck or not, not sure. I will play a few more games in different settings with these fixes to see what happens.

**Comment by davenye** [comment]
Thanks for that. I am somewhat devastated that it didn't help. I have had two very stable games (not built from that branch but from what *should* be essentially the same code). I hope to give it another try as soon as I get a chance.

**Comment by raphaell666** [comment]
Sorry but I erased the log files from that game in particular. Next game we get desyncs I will store the logs, the savefile and the modpack we use and attach them here. 

If you need to check if I did something wrong with the DLL code, the version of the DLL I am using is based on the repository in my account (I'm constantly updating it with the changes): https://github.com/raphaell666/Community-Patch-DLL

**Comment by davenye** [comment]
Just the all logs should be enough for my purposes at least. I am unlikely to load a save.

I doubt you did anything wrong.

**Comment by raphaell666** [comment]
@davenye I got the logs from another game that we were playing yesterday, that we got to turn 40 and were already having desyncs, so we quit.
[AutoSave_0040 BC-2400.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1940041/AutoSave_0040.BC-2400.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1940045/Logs.zip)

For my own future reference, we were playing with the version "VP_0420_d_mpfix" of the modpacks that I create.

I was playing on my gaming computer, which did not have all the logging options active, but I think the one that interests you the most is `net_message_debug.log`, right? If you need any other logs that are not there let me know so I can activate them for my next game.

Thank you for your time.

**Comment by raphaell666** [comment]
@davenye 

Good and bad news: 

The good news is today we played a Large map with 2 players + 8 AI + 20 city-states + barbarians, and had literally zero resyncs up to turn 100 which is when we stopped cause we have to sleep. Will continue probably on Wednesday. 

The bad news is that, regarding the mod and the DLL, from yesterday to today nothing significant has actually changed as far as I know (I included some new commits from G's master repo, and activated your newest fix). I really have no idea why we had no desyncs at all today, this is a huge contrast compared to yesterday when we were having desyncs literally every turn.

Hmm I think the biggest change is that I activated all logging options available (?).

**Comment by davenye** [comment]
That makes me feel a bit better...sort of 😔

I also always have all logging on all machines. You would hope it wouldn't affect the game but stranger things have happened!

If you have run the debugger you will see illegal memory access exceptions flying around in the EXE code, who knows if these are causing bizarre problems for us. It is worrisome after seeing the attitude to such matters in existing Firaxis code in the DLL. Of course we can't rule out me (or someone else) having screwed something up royally.

As for your earlier post about the logs I am interested in - when looking at desyncs I look at all log files from all machines. Logs from only one machine aren't all that helpful since we are really concerned with the differences between the machines.

**Comment by LoneGazebo** [comment]
Most of the memory access errors are benign checks being made by sound, graphic or UI update routines. Most of them just mean a null value was detected and tossed out.

**Comment by raphaell666** [comment]
@davenye 

We resumed the game from yesterday (we were actually at turn 88), and got two resyncs back to back in  two turns soon after the load. The main difference from the other day is that now we were playing on LAN rather than on separate physical locations (though I was still connecting through the civ "Internet" interface, not local network, doesn't seem to make any difference either way from previous experiences).  

I would expect that as the ping was far smaller (down to < 1 ms from 30 ms) that the connection would be more stable and that we would get less resyncs, but alas Civilization V does not work like that apparently.

I will attach the logs from both computers to this post, hope it helps. I will try taking a look at them too but I do not have any experience doing this.

[Logs_0424_A.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1944891/Logs_0424_A.zip)

**Comment by raphaell666** [comment]
The host was computer A, and I see an impressive amount of "out of sync" messages in the logs of computer B. 

<details>

 <summary>All the out of sync messages in the log of computer B</summary>

```
Line 2315: [450.593] DBG: City out of sync. Player=7, Name=TXT_KEY_CITY_NAME_ISTANBUL, id=1120, X=24, Y=29
Line 2316: Variable Out Of Sync : CvCity::m_vClosestNeighbors
Line 2318: [450.593] DBG: City out of sync. Player=7, Name=TXT_KEY_CITY_NAME_EDIRNE, id=1284, X=23, Y=21
Line 2319: Variable Out Of Sync : CvCity::m_vClosestNeighbors
Line 2323: [450.593] DBG: City out of sync. Player=7, Name=TXT_KEY_CITY_NAME_ANKARA, id=1379, X=20, Y=25
Line 2324: Variable Out Of Sync : CvCity::m_vClosestNeighbors
Line 2326: [450.593] DBG: City out of sync. Player=7, Name=TXT_KEY_CITY_NAME_BURSA, id=1538, X=18, Y=28
Line 2327: Variable Out Of Sync : CvCity::m_vClosestNeighbors
Line 2329: [450.593] DBG: City out of sync. Player=7, Name=TXT_KEY_CITY_NAME_KONYA, id=1584, X=24, Y=25
Line 2330: Variable Out Of Sync : CvCity::m_vClosestNeighbors
Line 2335: [450.593] DBG: City out of sync. Player=8, Name=TXT_KEY_CITY_NAME_GRONINGEN, id=1521, X=28, Y=55
Line 2336: Variable Out Of Sync : CvCity::m_iResourceDemanded
Line 2417: [450.593] DBG: Unit out of sync. Player=3, Name=Warrior, id=1186, X=83, Y=28
Line 2418: Variable Out Of Sync : CvUnit::m_iDamage
Line 2421: [450.593] DBG: Unit out of sync. Player=3, Name=Warrior, id=1186, X=83, Y=28
Line 2422: Variable Out Of Sync : CvUnit::m_iDamageTakenThisTurn
Line 2426: [450.593] DBG: Unit out of sync. Player=3, Name=Warrior, id=1155, X=86, Y=29
Line 2427: Variable Out Of Sync : CvUnit::m_iDamage
Line 2430: [450.593] DBG: Unit out of sync. Player=3, Name=Warrior, id=1155, X=86, Y=29
Line 2431: Variable Out Of Sync : CvUnit::m_iDamageTakenThisTurn
Line 2478: [450.593] DBG: Unit out of sync. Player=6, Name=Spearman, id=1479, X=72, Y=25
Line 2479: Variable Out Of Sync : CvUnit::m_iArmyId
Line 2486: [450.593] DBG: Unit out of sync. Player=6, Name=Warrior, id=1161, X=70, Y=29
Line 2487: Variable Out Of Sync : CvUnit::m_eTacticalMove
Line 2490: [450.593] DBG: Unit out of sync. Player=6, Name=Warrior, id=1161, X=70, Y=29
Line 2491: Variable Out Of Sync : CvUnit::m_eActivityType
Line 2506: [450.593] DBG: Unit out of sync. Player=7, Name=Spearman, id=1391, X=27, Y=24
Line 2507: Variable Out Of Sync : CvUnit::m_iDamage
Line 2510: [450.593] DBG: Unit out of sync. Player=7, Name=Spearman, id=1391, X=27, Y=24
Line 2511: Variable Out Of Sync : CvUnit::m_iDamageTakenThisTurn
Line 2519: [450.593] DBG: Unit out of sync. Player=7, Name=Spearman, id=1572, X=28, Y=30
Line 2520: Variable Out Of Sync : CvUnit::m_iGarrisonCityID
Line 2528: [450.593] DBG: Unit out of sync. Player=7, Name=Warrior, id=1319, X=33, Y=45
Line 2529: Variable Out Of Sync : CvUnit::m_iX
Line 2532: [450.593] DBG: Unit out of sync. Player=7, Name=Warrior, id=1319, X=33, Y=45
Line 2533: Variable Out Of Sync : CvUnit::m_iMissionAIX
Line 2601: [450.609] DBG: Unit out of sync. Player=30, Name=Warrior, id=1150, X=74, Y=46
Line 2602: Variable Out Of Sync : CvUnit::m_eTacticalMove
Line 2605: [450.609] DBG: Unit out of sync. Player=30, Name=Warrior, id=1150, X=74, Y=46
Line 2606: Variable Out Of Sync : CvUnit::m_eActivityType
Line 2661: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1658, X=85, Y=48
Line 2662: Variable Out Of Sync : CvUnit::m_iX
Line 2665: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1658, X=85, Y=48
Line 2666: Variable Out Of Sync : CvUnit::m_eFacingDirection
Line 2669: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1658, X=85, Y=48
Line 2670: Variable Out Of Sync : CvUnit::m_iMissionAIX
Line 2673: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1658, X=85, Y=48
Line 2674: Variable Out Of Sync : CvUnit::m_iMissionAIY
Line 2677: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1658, X=85, Y=48
Line 2678: Variable Out Of Sync : CvUnit::m_eMissionAIType
Line 2681: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1658, X=85, Y=48
Line 2682: Variable Out Of Sync : CvUnit::m_eActivityType
Line 2688: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1593, X=84, Y=48
Line 2689: Variable Out Of Sync : CvUnit::m_iX
Line 2692: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1593, X=84, Y=48
Line 2693: Variable Out Of Sync : CvUnit::m_iLastMoveTurn
Line 2696: [450.609] DBG: Unit out of sync. Player=63, Name=Hand-Axe, id=1593, X=84, Y=48
Line 2697: Variable Out Of Sync : CvUnit::m_eFacingDirection
Line 2710: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2711: Variable Out Of Sync : CvUnit::m_eUnitType
Line 2714: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2715: Variable Out Of Sync : CvUnit::m_iX
Line 2718: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2719: Variable Out Of Sync : CvUnit::m_iY
Line 2722: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2723: Variable Out Of Sync : CvUnit::m_iMoves
Line 2726: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2727: Variable Out Of Sync : CvUnit::m_iExperienceTimes100
Line 2730: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2731: Variable Out Of Sync : CvUnit::m_iLevel
Line 2734: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2735: Variable Out Of Sync : CvUnit::m_iOriginCity
Line 2738: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2739: Variable Out Of Sync : CvUnit::m_iExtraCombatPercent
Line 2742: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2743: Variable Out Of Sync : CvUnit::m_iExtraCityAttackPercent
Line 2746: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2747: Variable Out Of Sync : CvUnit::m_iFlankAttackModifier
Line 2750: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2751: Variable Out Of Sync : CvUnit::m_iExperiencePercent
Line 2754: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2755: Variable Out Of Sync : CvUnit::m_iBaseCombat
Line 2758: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2759: Variable Out Of Sync : CvUnit::m_eFacingDirection
Line 2762: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2763: Variable Out Of Sync : CvUnit::m_iNoDefensiveBonusCount
Line 2766: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2767: Variable Out Of Sync : CvUnit::m_iCanMoveAfterAttackingCount
Line 2770: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2771: Variable Out Of Sync : CvUnit::m_iHPHealedIfDefeatEnemy
Line 2774: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2775: Variable Out Of Sync : CvUnit::m_eTacticalMove
Line 2778: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2779: Variable Out Of Sync : CvUnit::m_iMissionAIX
Line 2782: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2783: Variable Out Of Sync : CvUnit::m_iMissionAIY
Line 2786: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2787: Variable Out Of Sync : CvUnit::m_eMissionAIType
Line 2790: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2791: Variable Out Of Sync : CvUnit::m_eActivityType
Line 2794: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2795: Variable Out Of Sync : CvUnit::m_eUnitAIType
Line 2798: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2799: Variable Out Of Sync : CvUnit::m_eCombatType
Line 2802: [450.609] DBG: Unit out of sync. Player=5, Name=Worker, id=1673, X=31, Y=39
Line 2803: Variable Out Of Sync : CvUnit::m_iLastGameTurnAtFullHealth
Line 2821: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2827: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2831: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2839: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2845: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2852: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2856: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2863: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iCachedValueOfPeaceWithHuman
Line 2866: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2872: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2879: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2883: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2887: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2891: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2895: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2899: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2905: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2911: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2915: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2919: [450.609] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2925: [450.625] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2929: [450.625] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2933: [450.625] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2937: [450.625] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 2941: [450.625] DBG: Variable Out Of Sync : CvPlayer::m_iMilitaryMight
Line 2944: [450.625] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 5844: [592.093] DBG: City out of sync. Player=7, Name=TXT_KEY_CITY_NAME_ANKARA, id=1379, X=20, Y=25
Line 5845: Variable Out Of Sync : CvCity::m_hGarrison
Line 5961: [592.109] DBG: Unit out of sync. Player=3, Name=Warrior, id=1186, X=84, Y=27
Line 5962: Variable Out Of Sync : CvUnit::m_iDamage
Line 5993: [592.109] DBG: Unit out of sync. Player=5, Name=Spearman, id=1494, X=28, Y=44
Line 5994: Variable Out Of Sync : CvUnit::m_eTacticalMove
Line 5997: [592.109] DBG: Unit out of sync. Player=5, Name=Spearman, id=1494, X=28, Y=44
Line 5998: Variable Out Of Sync : CvUnit::m_eActivityType
Line 6009: [592.109] DBG: Unit out of sync. Player=5, Name=Archer, id=1363, X=32, Y=40
Line 6010: Variable Out Of Sync : CvUnit::m_eActivityType
Line 6042: [592.109] DBG: Unit out of sync. Player=7, Name=Spearman, id=1440, X=20, Y=29
Line 6043: Variable Out Of Sync : CvUnit::m_eFacingDirection
Line 6082: [592.109] DBG: Unit out of sync. Player=9, Name=Scout, id=1361, X=35, Y=43
Line 6083: Variable Out Of Sync : CvUnit::m_iX
Line 6086: [592.109] DBG: Unit out of sync. Player=9, Name=Scout, id=1361, X=35, Y=43
Line 6087: Variable Out Of Sync : CvUnit::m_iExperienceTimes100
Line 6090: [592.109] DBG: Unit out of sync. Player=9, Name=Scout, id=1361, X=35, Y=43
Line 6091: Variable Out Of Sync : CvUnit::m_iMissionAIX
Line 6149: [592.109] DBG: Unit out of sync. Player=36, Name=Spearman, id=1563, X=27, Y=12
Line 6150: Variable Out Of Sync : CvUnit::m_iDamage
Line 6161: [592.109] DBG: Unit out of sync. Player=38, Name=Warrior, id=1062, X=87, Y=48
Line 6162: Variable Out Of Sync : CvUnit::m_iDamage
Line 6179: [592.109] DBG: Unit out of sync. Player=63, Name=Horseman, id=1649, X=29, Y=14
Line 6180: Variable Out Of Sync : CvUnit::m_iDamage
Line 6183: [592.109] DBG: Unit out of sync. Player=63, Name=Horseman, id=1649, X=29, Y=14
Line 6184: Variable Out Of Sync : CvUnit::m_iDamageTakenThisTurn
Line 6235: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6242: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6248: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6255: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6262: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6268: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6275: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6278: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_paiUnitClassMaking
Line 6279: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_paiBuildingClassMaking
Line 6281: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iFaith
Line 6284: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iFaithEverGenerated
Line 6287: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6291: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6298: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6302: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6306: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6310: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6316: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6320: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6324: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6331: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6337: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6341: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6345: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6349: [592.109] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6356: [592.125] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6363: [592.125] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6367: [592.125] DBG: Variable Out Of Sync : CvPlayer::m_iUnitProductionMaintenanceMod
Line 6370: [592.125] DBG: Variable Out Of Sync : CvPlayer::m_iNumMilitaryUnits
Line 6373: [592.125] DBG: Variable Out Of Sync : CvPlayer::m_iMilitaryMight
Line 6376: [592.125] DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved
Line 6379: [592.125] DBG: Variable Out Of Sync : CvPlayer::m_paiUnitClassCount
```
</details>
<p>

Lines 2300 to 3000 were the cause of the first resync, and from 5800 to 6400 the second one.

It seems like literally everything was going out of sync for some reason.

**Comment by davenye** [comment]
Thanks, that is what I am after. I shall see what I can see.

**Comment by LoneGazebo** [comment]
If you were on 4-20 it may or may not have been related to the CTD @Infixo fixed (as it was a memory error). Anything's possible.

**Comment by raphaell666** [comment]
@LoneGazebo Could be. I will see if I can update the DLL with those fixes and continue that game.

**Comment by LoneGazebo** [comment]
@raphaell666 if that is the case (re: saves causing resyncs), my theory is that one of the kstream loaders and/or m_syncarchives are creating some garbage memory elements. We'd need to check all instances of these, such as those in

CvGame
CvPlayer
CvUnit

etc. etc. and look for situations in which the kstream << >> are not parallel and/or a bad value is being dumped into the m_syncarchive. That's...not going to be fun.

**Comment by davenye** [comment]
I have had a little bit of a look at stuff related to this change today and spotted some problems with the ordering (not things that should cause issues after loading though). I have made a few alterations and hope to finally have a game this weekend.

@raphaell666, Please note that 3 of my changes did modify the save layout but I think you would have had all of them before starting you game. There could be issues with the loading of diplo reqs but I have not ran into any myself. Regular autosaves will not have diplo reqs in them - they will only be present mid-turn. You are almost certainly doing more testing than I have been in the week so you are more likely to have ran into issues. I will keep plenty of saves from my session to see if they have any trouble getting loaded.

I apologise, I have not looked at the logs yet.

**Comment by raphaell666** [comment]
@LoneGazebo @davenye Update: Good news, we continued my latest game by loading from an autosave, and indeed we're not having any desyncs at all this time. The game now has been played from zero to turn 108 without desyncs, then reloaded from an autosave and played up to turn 126 without desyncs. We will continue it this weekend.

Compared to the previous game, we played up to turn 88 without desyncs, then reloaded from a forced save/double save and we were having desyncs/resyncs immediately at turns 89-90-91.

This is still definitely not enough of a sample size to be certain, could just be luck, but I feel that we are onto something here.

I will upload the logs from this latest game here. I noticed that we were getting a lot of `DBG: Variable Out Of Sync : CvPlayer::m_iLastSliceMoved` messages (like thousands of them), but this was not causing issues nor resyncs so far. We will see what happens when we continue.

> There could be issues with the loading of diplo reqs but I have not ran into any myself. Regular autosaves will not have diplo reqs in them - they will only be present mid-turn.

But usually when loading an autosave the game will replay the AI's turns, so they will send new diplo reqs, right? Or do you mean human diplo reqs? In that case, I think intuitively it would be somewhat expected that we would lose the human diplo reqs when reloading the autosave (as it replays the AI turns). If it is not something easy to fix then I think you definitely can focus on other things.

I haven't run into any issues at all so far, everything is pristine.

**Comment by davenye** [comment]
That is great to hear! Sounds like we might be ready to get some wider testing done soon. There seems to be a bit of interest in MP on the civfanatics at the moment, it will be good timing.

G might be able to tell us something about the m_iLastSliceMoved warnings, I think he finds them benign. I do not yet understand why they occur or why they don't seem to be a real problem. I will be looking at that area of code in relation to this change so maybe I will know more soon.

Yes, with proper (auto)saves the AI will replay their turn, well really they will play their turn since as far as the save is concerned their turns never happened. The "post" saves or "forced" saves are made after AI have had their turn and need to have any requests that were made saved to the file so they can be restored when loaded.
I would not be surprised if there are other issues with saving mid-turn. There appears to be a lot of state that is not serialised, which is likely to cause problems but I think these should be considered existing bugs as I expect that they could also be an issue for single player saves (not that I have looked at SP much).

**Comment by LoneGazebo** [comment]
Some sync errors are benign and or controlled before, as things like turn slice do in fact go out of sync (since it is a client side change that has to be passed to the host). 

Enthused about the changes. Make sure you’ve pushed any relevant changes, including lua/xml changes. If you don’t know where or how to add them to the CP’s VFS let me know. 

G

**Pull request merged**
