### PR TITLE
fix bug where plot reveal was dependant on active player

### PR DESCRIPTION
**Pull request by davenye**
Issue when revealing plots during plot visibility count update.

Return value from CvPlot::setRevealed is more nuanced than simply
returning whether the plot is being revealed to the team.

Now using a simple check for when deciding on whether the explore plots list needs amending.

This will be responsible for a large number of desyncs for people who autoexplore. When autoexploring the unit could choose a different plot to explore since it is selecting from a different set of potential plots as the active player has reveal plots that the other machines do not.

This bug causes all sorts of problems, particularly desyncs in MP.
While the position is possibly synced by host, the visibility of the
plots is not. This means things like barb camps get spawned in different
locations on different machines, which is a big problem. I think bug is the catalyst for a great amount of drift of all sorts.

Also, it causes the AI to explore sub optimally...gonna double check this though!

Will result in slightly more processing but it is the right thing to do.

EDIT:
Just remembered that I need to add the preprocessor code for conditional compilation of the bugfix.

Also attempted to be more coherent in the above text.

### CODE REVIEW

**Comment by LoneGazebo** [comment]
@davenye not a great place to post this but there’s a 32-64 bit sign issue when you compile your DLL changes for 43 civs - compile for 43 and you’ll see it.

**Comment by LoneGazebo** [comment]
I didn’t get a chance to fix it before I left

**Comment by davenye** [comment]
@LoneGazebo, I am pretty sure I know where the problem is going to be but I cannot see how to compile for 43.

**Comment by LoneGazebo** [comment]
@davenye custommodsglobal.h in the assets part of the project viewer.

**Comment by Iamblichos** [comment]
@davenye  this is where it happens if you haven't had a chance to look.....need something like this....

```
void updateKnownPlayersTable()
{
	// Playing it safe here, don't want to introduce a bug due to not knowing all the code paths and trying to save a few cycles/bytes
	s_knownPlayersTable.clear();
	s_knownPlayersTable.resize(MAX_MAJOR_CIVS);
	for (int i = 0; i < MAX_MAJOR_CIVS; i++) {
		KnownPlayersBitArray bitarray = 0;
		const CvTeam& kTeam = GET_TEAM((TeamTypes)i);

		for (int j = 0; j < MAX_MAJOR_CIVS; j++) {
			if (i == j || kTeam.isHasMet((TeamTypes)j))
#if defined(MOD_GLOBAL_MAX_MAJOR_CIVS)
				bitarray |= 1LL << j;
#else
				bitarray |= 1 << j;
#endif
		}
		s_knownPlayersTable[i] = bitarray;
	}
}
```
```
bool isKnownPlayer(PlayerTypes eA, PlayerTypes eB) {
	// table will be empty if GAMEOPTION_KEEP_UNMET_PLAYERS_UNKNOWN, i.e. not keeping track of unmet players and consider all to be met for the purposes of PreGame UI.
	if (s_knownPlayersTable.empty()) return true;
	if (eA < 0 || eB < 0) return true; // erring on the side of caution
	if ((size_t)eA >= s_knownPlayersTable.size() || (size_t)eB >= s_knownPlayersTable.size()) return true; // erring on the side of caution
#if defined(MOD_GLOBAL_MAX_MAJOR_CIVS)
	bool bKnown = s_knownPlayersTable[eA] & (1LL << eB);
#else
	bool bKnown = s_knownPlayersTable[eA] & (1 << eB);
#endif
	return bKnown;
}
```

**Comment by davenye** [comment]
My Visual Studio is still half busted (IntelliSense won't function) but I inspected the code and believe the fix is sound based on the fact that setRevealed was always returning true if the plot revealed status for the activeplayer was changing. Now I am doing that test for all players instead,

A strange thing I did notice was that a explore list update would be triggered if the plot went from revealed to *not* revealed. I am not doing that, maybe I should (easy change, obviously) but can this even happen? Gonna merge this anyway.

I have finally checked in the conditional compilation version (appears much higher up in this thread).

**Pull request merged**
