### PR TITLE
Cross your fingers.

### PR DESCRIPTION
**Pull request by Iamblichos**

### CODE REVIEW

**Comment by LoneGazebo** [comment]
Let's test SP and MP before sending out.

**Comment by Iamblichos** [comment]
Absolutely. I tested SP last night...but wouldn't hurt to test again.

**Comment by Iamblichos** [comment]
SP seems to be working fine.

**Comment by LoneGazebo** [comment]
Great! I'll be out of pocket this evening but we can test MP tomorrow (if you are free) and, if all goes well, we can make modpacks and distribute.

**Pull request merged**
