### PR TITLE
Set workboat prereq resources to 0

### PR DESCRIPTION
**Pull request by nobubblegums**
Set workboat prereq resources to 0 instead of "false". Doesn't change anything, but makes the table look better

### CODE REVIEW

**Comment by RecursiveVision** [comment]
The default is "true" in the code and this is not good style.

**Comment by LessRekkless** [comment]
This is the difference between doing something in SQL and XML.  "true"/"false" in XML is automatically converted to 1/0 in the table.

image

**Comment by LessRekkless** [comment]
The only widespread use of 'true'/'false' in SQL is the events table. Everything else is 1/0.

**Comment by RecursiveVision** [comment]
I realized this later but forgot to merge this. Done.

**Pull request closed without merging**
