### PR TITLE
Promotion Changes (help)

### PR DESCRIPTION
**Pull request by Mileslewis**
I really don't understand Github I literally just pulled from the Gazebo master to mine and then changed CvUnit.cpp and now it's being crazy saying they are completely different. What did I do wrong?

### CODE REVIEW

**Comment by RecursiveVision** [comment]
@Mileslewis You need to use "Merge into current branch..." on Github Desktop or a similar tool. Alternatively, whenever master branch is updated, delete your local repository and redownload a fresh copy.

**Comment by RecursiveVision** [comment]
I'll add your changes to my pull request this time.

**Comment by Mileslewis** [comment]
So first thing I did was do a pull request on browser from Gazebo master to mine.
Then I opened up desktop and used fetch origin which seemed to retrieve the new files. Was that not correct?

I guess it's easier in future i'll just delete my old files and download new ones if that works better.

**Comment by Mileslewis** [comment]
> I'll add your changes to my pull request this time (since I've also modified CvUnit - this way it avoids merge errors).

Okay cool thanks, all of my changes were within the:    
void CvUnit::AI_promote
int CvUnit::AI_promotionValue
functions.

**Comment by RecursiveVision** [comment]
> 
> 
> So first thing I did was do a pull request on browser from Gazebo master to mine.
> Then I opened up desktop and used fetch origin which seemed to retrieve the new files. Was that not correct?
> 
> I guess it's easier in future i'll just delete my old files and download new ones if that works better.

@Mileslewis Open up Github Desktop and use this tool - when prompted, replace your files with the master branch of the files.
Screenshot

**Comment by RecursiveVision** [comment]
Pushed your changes. You forgot to initialize iNextValue so it wasn't building, fixed that for you.

Push commit:
https://github.com/LoneGazebo/Community-Patch-DLL/pull/7017/commits/7f47b1a76473f49ac3bceff32ec154f42ccfa03d

**Pull request closed without merging**
