### PR TITLE
VMC 17/02/20

### PR DESCRIPTION
**Pull request by HungryForFood**
Syncing over Whoward's VMC changes up to the latest version, v94.

- Updated with automaton worker stuff (Buildings, Techs, Traits, Policies, Lua methods) from VMC v90.
- Updated with Lua hook for ranged attack (UnitCanRangeAttackAt) from VMC v90.
- Excluded diplomacy AI stuff (to not conflict with HeathcliffWarriors' work).
- Excluded tech cost overflow stuff (we have our own fix).
- Added PlayerDoneTurn Lua hook (from VMC v94).
- Added SetRoutePillaged Lua method (from VMC v94).

### CODE REVIEW

**Comment by HeathcliffWarriors** [comment]
@HungryForFood Could you point me to the changes to diplomacy AI? Perhaps there's something useful we could use.

**Comment by HungryForFood** [comment]
See this [commit](https://github.com/whoward69/DLL-VMC/commit/8db8b5add78ff3a03df590afabd481260f311849), in CvDiplomacyAI.cpp.

Seems to just be enabling an option to disable AI deal requests.

**Comment by LoneGazebo** [comment]
prolly the STFU stuff. I ignore that.

@HungryForFood there was an issue with savegames with this, I had to refactor it a bit. All well now, though.

G

**Comment by HungryForFood** [comment]
Oops, should have tested save games.

**Pull request merged**
