### PR TITLE
RecomputeFollowers() 

### PR DESCRIPTION
**Pull request by LessRekkless**
@ilteroi
RecomputeFollowers() has been added after AddReligiousPressure().  There's no point in recomputing twice in succession.

### CODE REVIEW

**Comment by RecursiveVision** [comment]
I removed the extra calls outside of AddReligiousPressure() instead. Fewer lines of code to deal with.

**Comment by LessRekkless** [comment]
@ilteroi specifically moved them outside AddReligiousPressure() on e0b6d886d92975104869d7f0cecc007917f10425 on 2021/12/31.

**Comment by RecursiveVision** [comment]
shrug, don't think he'll mind

**Comment by RecursiveVision** [comment]
Okay I stand corrected

**Pull request merged**
