### PR TITLE
Fixes for #4220 and #4222

### PR DESCRIPTION
**Pull request by Infixo**

### CODE REVIEW

**Comment by LoneGazebo** [comment]
Danke. Did you merge @iamblichos fix? If so I’ll hotfix today.

**Comment by Infixo** [comment]
If you mean that Tradition updates then no.

**Comment by Iamblichos** [comment]
I've got a number of little issues I've brought up today. As far as the Policy stuff goes for Tradition, Autocracy, Order, and Freedom, I'll change the DLL and Infixo can do the SQL code.

**Comment by Iamblichos** [comment]
@LoneGazebo looks like you already have a check for the Tradition buildings in CvBuildingClasses.cpp CapitalOnly, so we won't need a Policy check.

**Pull request merged**
