### PR TITLE
Some Typo Fixes

### PR DESCRIPTION
**Pull request by Aqinu**

### CODE REVIEW

**Comment by Aqinu** [comment]
**City Revolt Fix**
Because of that additional condition, the game used the vanilla string (instead of already implemented vp version).

**Before Fix**



**After Fix**

**Comment by Aqinu** [comment]
@LoneGazebo what is going on, some pull request that were merged don't appear at all in this version? (#5704 #5694)

**Comment by LoneGazebo** [comment]
You likely made the pull request after I’d merged for master on the current beta. Apologies.

**Comment by Aqinu** [comment]
@LoneGazebo Is there something that I can do to avoid this from happening again? (something that can tell me that is safe to make a pull request)

**Pull request merged**
