### PR TITLE
Fix a CTD

### PR DESCRIPTION
**Pull request by Iamblichos**

### CODE REVIEW

**Comment by LoneGazebo** [comment]
Manually merged, no need for full merge.

**Comment by Iamblichos** [comment]
@LoneGazebo 

Are you having a lot of issues? Weekend's coming and I'd like to get modpacks built this afternoon, if possible, we can shore up the minor to do stuff later, I would think.

If there's major issues, never mind.

**Comment by LoneGazebo** [comment]
No, actually doing a 'final' test right now, then I'm going to start prepping for release.

**Comment by Iamblichos** [comment]
If you don't mind syncing up to GitHub your final test, I can get the ball rolling.

**Comment by LoneGazebo** [comment]
@Iamblichos done and done.

**Comment by Iamblichos** [comment]
Good job bro!

**Comment by LoneGazebo** [comment]
Yay!

**Comment by LoneGazebo** [comment]
Grab latest. Small CTD fix.

**Comment by Iamblichos** [comment]
Thanks!

**Comment by LoneGazebo** [comment]
You are going to hate me, but one more hotfix incoming. Small.

**Comment by Iamblichos** [comment]
Ah it's cool man....as long as we got the release out there and people playing. Shore up the minor stuff on the way.

**Pull request closed without merging**
