### PR TITLE
ModderRequests 31/12/20

### PR DESCRIPTION
**Pull request by HungryForFood**
## Lua methods
- Added Lua method Player.GetNumUnitsOfType(UnitType Unit, bool bIncludeBeingTrained = false). Counts the number of UnitType the player has. bIncludeBeingTrained  is optional.
- Added Lua method Player.GetNumUnitPromotions(PromotionType iPromotion). Counts the number of units a player owns which have the specified promotion.

## Bug fixes and misc
- UnitPromotions_YieldFromScouting now works with YIELD_GOLDEN_AGE_POINTS, YIELD_GREAT_GENERAL_POINTS, and YIELD_GREAT_ADMIRAL_POINTS.
- Added column 'IsNoCoast' to Buildings.
- Fixed Building_ResourcePlotsToPlace not placing resources on plots without improvements.
- Yields from Trait_YieldFromBarbarianCampClears now correctly go to the nearest city.

## New belief tables
- Added Belief_FreePromotions (BeliefType, PromotionType). For pantheons or followers. Units trained in cities with the religion will gain the referenced promotions. Also applies retroactively to units trained before conversion. Requires RELIGION_EXTENSIONS in CustomModOptions.
- Added Belief_YieldFromTechUnlock (BeliefType, YieldType, Yield). Intended for founder beliefs. Instant yields when researching technology.
- Added Belief_YieldFromImprovementBuild (BeliefType, YieldType, Yield, IsEraScaling). Intended for pantheons or followers. Instant yields when an improvement finishes building. Requires RELIGION_EXTENSIONS in CustomModOptions.
- Added Belief_YieldFromPillageGlobal (BeliefType, YieldType, Yield, IsEraScaling). Intended for pantheons or followers. Instant yields when a unit from any city pillages. Requires RELIGION_EXTENSIONS in CustomModOptions.

Save game compatible.

### CODE REVIEW

**Comment by HungryForFood** [comment]
For modder testing.

[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5755008/1.Community.Patch.zip)

**Comment by pineappledan** [comment]
omg Yay!!
Thank you so much for adding these!

**Comment by adaneslavo** [comment]
Double Yay! One for ResourcePlotsToPlace fix and second for IsNoCoast :P.

**Comment by RecursiveVision** [comment]
Merged into rsi branch.

**Pull request closed without merging**
