### PR TITLE
Autovariables pull

### PR DESCRIPTION
**Pull request by RecursiveVision**

### CODE REVIEW

**Comment by LoneGazebo** [comment]
@IanE9, once we test CvUnit, do you want to apply the same method to CvCity and CvPlayer? I know they won't have as much of an impact, but the consistency would be nice.

**Comment by LoneGazebo** [comment]
I also wonder if the portability of these memory changes will improve multiplayer stability re: sync issues.

**Comment by IanE9** [comment]
I would like to do the same with the other classes, I'll need to test multiplayer pretty extensively though. I got around to examining Fraxis' interfaces for syncing multiplayer just before I went to sleep last night and ended up deeming it pretty dreadful and I'm going to have to retrofit some stuff to make sure all the new code I have remains compatible with them. It probably wont impact sync stability much, but understanding the system may make it easier for me to debug desyncs.

**Comment by RecursiveVision** [comment]
It would be awesome if we could play VP in multiplayer. :D 

Also if you're fixing serialization on a larger scale maybe you'd be able to find why switching between release and debug configs makes saves impossible to load, sometimes but not always. I have no clue why that happens but it sure makes debugging a pain.

Serialization in general is pretty bad...

**Comment by LoneGazebo** [comment]
You can reproduce the release->debug issue by compiling release, starting game, saving, then trying to load on a debug DLL..

**Comment by RecursiveVision** [comment]
I've sometimes been able to get it to work, and it seems more likely in the early game. That's what makes it so annoying...

Perhaps I can ask for unmodded late game saves on the forum and test them out until the behavior is identified.

**Comment by RecursiveVision** [comment]
#7777, #7753

These are from the 4/16 version...

**Comment by IanE9** [comment]
> You can reproduce the release->debug issue by compiling release, starting game, saving, then trying to load on a debug DLL..

I only asked for a save because the saves I've been using for testing have loaded no problem in both configs ^^'

> These are from the 4/16 version...

Recent saves compatible with the current version are best. I tried #7777's save and it claims to have DLC I don't anyway, so I'll try to reproduce the issue locally later.

**Comment by RecursiveVision** [comment]
@IanE9 Do you own all of the Civ V DLC?

Might be other mods affecting savegame compatibility...

**Comment by IanE9** [comment]
The only DLCs I don't have are map packs. I hope that's not impacting it but maybe.

**Pull request merged**
