### PR TITLE
Fix for issue #5488

### PR DESCRIPTION
**Pull request by Aqinu**
Fix for Combat Preview Panel Bonuses Overflow, I tested it and it does work.

**Additional changes:**
Also changed YOUR STRENGTH value to be rounded to one decimal after the point instead of two (**see screenshots 1 and 2** from **145.75** in **145.8**) this way doesn't go out of the panel.

**Known issues:**
One single problem I saw is that not always in the preview panel are shown 4 bonuses then the misc. one (as far as I tested didn't go less than 3 bonuses and one misc. bonus but remember that **misc. one doesn't appear when there are 4 bonuses or lower**), thats because some bonuses stack together into one name but each one of the bonuses is counted (i.e. you have Bonus 1 = 10% and Bonus 2 = 15% but they are displayed as a single bonus in form of Bonus 3 =25% but Bonus 1 and Bonus 2 as counted as two bonuses, even though are displayed as one).

I reduced this problem as much as I could by prioritizing some bonuses to be displayed like this:
1 Empire Unhappiness
2 GA/GG
3 Policy Bonuses
4 Monopoly
...
n Combat Bonus (I put is the last one so that doesn't cause these issues, cause this bonus stacks with multiple bonuses)

**Regardless now it will not go more than 6 rows in the panel (it will not overflow).**

**Here some screenshots:**

**Here test UnitvsCity with two decimal points, see that overflows**
Civ5Screen0037

**Here test UnitvsCity with one decimal point, now is better and rounded**
Civ5Screen0043

**Here test UnitvsCity**
Civ5Screen0048

**Here CityvsUnit (didn't manage to give bonuses to the AI but should still work)**
Civ5Screen0042

**Here test UnitvsUnit**
Civ5Screen0047

### CODE REVIEW

**Comment by ryanmusante** [comment]
Coolio

**Comment by TechpriestEnginseer** [comment]
But you have to make the change for all EnemyUnitPanel.lua tho. CP, CBP, the 43-civ version (EUI), the 43-civ version (non-EUI), 6a, 6b....

**Comment by Aqinu** [comment]
Yeah, all of those are all identical and I don't know if these has to be changed as well, wait for @LoneGazebo to confirm if this is the case then I will push the rest of them (just copy and paste no big deal...)

**Comment by TechpriestEnginseer** [comment]
All UI files of the same file name have to have similar changes for it to be approved.

**Comment by Aqinu** [comment]
So you are 100% sure that all of them must be pushed? OK then...

**Comment by Aqinu** [comment]
**Now the bonus Strategic Resource Monopoly is correctly aligned (with Fix for issue #5488 Part 3), see screenshot 3 from above where is not properly aligned**

Civ5Screen0049

**Comment by Aqinu** [comment]
Conflict caused, I guess by Terracotta Army Fix from previous @HeathcliffWarriors  pull request (just keep my change of it so that the wonders have the same format, in case you accept my improvements)...

**Pull request merged**
