### PR TITLE
More bugfixes

### LINKED ISSUE #9353: 2.7.3 - United Nations tooltip says "when reach Atomic Era", but actually required Information Era
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

2.7.3

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

You must reach the Information Era (and have the UN policy pased) to truly activate the United Nations. However, the popup note about the UN says Atomic Era.

image

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

### LINKED ISSUE #10120: Some building modifiers are not shown in Civilopedia
A picture is worth a thousand words.

Civ5Screen0031
Civ5Screen0032
Civ5Screen0033

### PR DESCRIPTION
**Pull request by axatin**
Fix incorrect pledge of protection messages

Civilopedia yield information and non-EUI tooltip cleanup (fix #10120)

Hide dummy building for spanish mission in civilopedia

Fix united nations requiring information era (fix #9353)

Improve espionage logging

### CODE REVIEW

**Comment by azum4roll** [comment]
Yield modifiers are supposed to show up in help text.

**Comment by axatin** [comment]
Yield modifiers are already shown in civilopedia, see the screenshots in #10120, only some types of yields were forgotten. They're also shown in building tooltips, check throme room for example. So they shouldn't be in mentioned in the text as well.

**Comment by azum4roll** [comment]
Defense, HP, supply, yield per pop etc. are also in tooltips, but they're still listed out in the text. Only yields are omitted.

**Comment by axatin** [comment]
Those are EUI-only additions to the tooltips.

Yield modifiers have always been in tooltips and not in texts. This is the vanilla workshop:

Screenshot (573)
Screenshot (574)

**Comment by azum4roll** [comment]
Vanilla text is known to be inconsistent (and sometimes wrong). See Temple of Artemis with the +10% food written on the help text but labelled as growth.

**Comment by axatin** [comment]
Then that's something that should be fixed in CP, if it isn't already. Still there's no reason to bloat up the help texts and make them less legible by putting there the same information as in the tooltips.

**Comment by azum4roll** [comment]
Will you be considering adding most of those to non-EUI tooltips as well? Better make it consistent.

**Comment by axatin** [comment]
Yes, I'll check it in more detail later and see what can be added to the non-EUI tooltips.

If you want, I can revert the text changes.

**Comment by azum4roll** [comment]
> If you want, I can revert the text changes.

Yes, please do. Better have it be consistent and change it in one go.

**Comment by axatin** [comment]
okay, done

**Pull request merged**
