### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Mileslewis**
Changed formula in CvPlayerTechs::GetResearchCost so that tech cost displayed should be closer to actual cost #6894

Removed tech overflow modifier by removing calculateresearchmodifier( from various places #6894

No longer count people you haven't met when working out tech modifier from known techs in calculateresearchmodifier(
-- Couldn't get it to ignore your own civ/team which is a bit annoying. Means you can never get up to 10% discount. -1 to iPossibleKnownCount would do the trick but it's pretty ugly.

Moved getUnitExtraCost in CvPlayer::getProductionNeeded(UnitTypes so that the flat production is added before modifiers. Affects settler costs on different gamespeeds.

Fixed Imperialism GPP bug. CvPlayer::getSpecificGreatPersonRateChangeFromMonopoly and CvPlayer::getSpecificGreatPersonRateModifierFromMonopoly #7293 

Fixed Imperialism Combat Strength bug in CvPlayer::UpdateMonopolyCache() #7120 
I just got rid of any extra combat bonus from imperialism. Not sure if you are meant to get a bonus 10% to combat bonuses you already get, doesn't mention this in the policy tooltip though.

added UpdateMonopolyCache into CvPlayerManager::Refresh so that monopolies work on reload. #7215 

Changed MINOR_FRIENDSHIP_RATE_MOD_SHARED_RELIGION to 50 to stop no friendship decay with shared religion. #7151
Literally just an xml value that was too high. Though perhaps the formula should be changed to multiplicative rather than additive modifiers to prevent this.

### CODE REVIEW

**Comment by RecursiveVision** [comment]
Mmm, commits from June...and changing files ilteroi and I have also changed. I foresee merge issues!

I'll just merge your changes into my own branch. :)

**Comment by RecursiveVision** [comment]
Done.

**Comment by Mileslewis** [comment]
It was all good right? Also how do I get rid of the old commits which aren't relevant anymore?

**Comment by RecursiveVision** [comment]
@Mileslewis There were no build errors. You *did* test it first, right?

To remove old commits just reclone master branch by deleting the fork and reforking/redownloading.

**Pull request closed without merging**
