### PR TITLE
Diplo Fixes & Improvements

### PR DESCRIPTION
**Pull request by HeathcliffWarriors**
@ilteroi Fixed build errors

### CODE REVIEW

**Comment by supermerill** [comment]
> The enormous amount of changes isn't notable, I just did Find "if(" and "switch(" and Replaced them with "if (" and "switch ("
just some little things to say:
 - why?
 - please do that in a separate pr, i can't see what "Diplo Fixes & Improvements" are. (github say "3,469 additions, 3,540 deletions not shown because the diff is too large. Please use a local Git client to view these changes." )
- why only one file? now the formatting isn't in sync with the other ones !!!! If you use a formatting tool, please tune it to the project current formatting to avoid rewriting everything!
- This break the history of changes (git blame), even more.

**Comment by HeathcliffWarriors** [comment]
@supermerill Oops :)

If you want to see what I changed, check out the first commit in #5886, which is visible without needing a local client. The other commits are just build error fixes and a couple improvements to the demand mechanic change.

As for why, the others were doing it, and IMO it's easier on the eyes with the space.

Doing it once also saves me from cluttering future edits with changes that are simply adding spaces.

**Comment by supermerill** [comment]
> As for why,  IMO it's easier on the eyes with the space.

I agree. But it's a open-source project with multiple opinions & hands.

> As for why, the others were doing it,

I looked at these two commits:
https://github.com/LoneGazebo/Community-Patch-DLL/commit/f7ee01c24b5369817f5d27726305938f0417b95d
https://github.com/LoneGazebo/Community-Patch-DLL/commit/3783d7f1f870984ebdbfaa486eca181335151322

It seems they don't care, as they sometimes use a space and sometimes not.

I'm not against formatting guidelines, clearly not. Also I'm not active enough to have any sort of voting power. But from a reader point of view, these big formatting updates on something that aren't enforced on anybody, are a bit distracting, because they can happen again and again, and it clutter the commits.

> If you want to see what I changed, check out the first commit in #5886

Thank you, it's better.

**Comment by HeathcliffWarriors** [comment]
@supermerill In any case it seems to have been reverted for the actual version, so just look at the 11-25 commit to see the full changes.

**Comment by LoneGazebo** [comment]
Yeah I hate cosmetic changes. :) they make commits look ugly.

**Pull request merged**
