### PR TITLE
New adjacency with builder AI support

### PR DESCRIPTION
**Pull request by KungCheops**

### CODE REVIEW

**Comment by azum4roll** [comment]
What's the point of making any of those functions static (rather than private)? You aren't calling them from outside the class.

**Comment by KungCheops** [comment]
> What's the point of making any of those functions static (rather than private)? You aren't calling them from outside the class.

The functions are static because they don't need to access any of the member variables of a CvBuilderTaskingAI object. Static doesn't mean you can call it outside of the class.

**Comment by KungCheops** [comment]
gonna move this to drafts, since rek is going to be changing the commits this is including

**Comment by KungCheops** [comment]
> @KungCheops Finally merged Rek's commits, you can finish this.

nice, will do tomorrow evening

**Pull request closed without merging**
