### PR TITLE
Delete unused deal item code & cleanup

### PR DESCRIPTION
**Pull request by RecursiveVision**
@LoneGazebo Removes all the code relating to unused deal items and all the superfluous MOD_EVENTS_WAR_AND_PEACE code, along with a few other cleanups.

Unfortunately wasn't able to do a second pass or test because the build is broken (issue in CvBuilderTaskingAI) but I did my best to be careful.

Deletes five memory values, so not savegame compatible.

### CODE REVIEW

**Comment by LoneGazebo** [comment]
CvBuilderTaskingAI
What's the issue?

**Comment by RecursiveVision** [comment]
It won't build - I'll pull up the error screen for you.

**Comment by RecursiveVision** [comment]
```
1>C:\Users\[My User]\Documents\GitHub\Community-Patch-DLL\FirePlace\include\Fireworks/FDataStream.h(266): error C2664: 'void FDataStream::Read(YouMustImplementASerializeOperatorForThisTypeError &)' : cannot convert parameter 1 from 'CvBuilderTaskingAI::RoutePlotContainer' to 'YouMustImplementASerializeOperatorForThisTypeError &'
1>        CvBuilderTaskingAI.cpp(172) : see reference to function template instantiation 'FDataStream &FDataStream::operator >><CvBuilderTaskingAI::RoutePlotContainer>(T &)' being compiled
1>        with
1>        [
1>            T=CvBuilderTaskingAI::RoutePlotContainer
1>        ]
1>C:\Users\Admin\Documents\GitHub\Community-Patch-DLL\FirePlace\include\Fireworks/FDataStream.h(252): error C2664: 'void FDataStream::Write(const YouMustImplementASerializeOperatorForThisTypeError &)' : cannot convert parameter 1 from 'const CvBuilderTaskingAI::RoutePlotContainer' to 'const YouMustImplementASerializeOperatorForThisTypeError &'
1>        Reason: cannot convert from 'const CvBuilderTaskingAI::RoutePlotContainer' to 'const YouMustImplementASerializeOperatorForThisTypeError'
1>        Source or target has incomplete type
1>        CvBuilderTaskingAI.cpp(184) : see reference to function template instantiation 'FDataStream &FDataStream::operator <<<CvBuilderTaskingAI::RoutePlotContainer>(const T &)' being compiled
1>        with
1>        [
1>            T=CvBuilderTaskingAI::RoutePlotContainer
1>        ]
```
69f93e0538a326fa84295c040969d394

**Comment by LoneGazebo** [comment]
If you're missing a serializer make sure your local repo has the util and framework updates.

**Comment by RecursiveVision** [comment]
I'll redownload and see if it works.

**Comment by RecursiveVision** [comment]
Tried again using a fresh copy of the repository, master branch...no dice, still refuses to build.

My IDE is doing this now when I load the solution file (ever since I updated to the latest VS 2019 version earlier today), which didn't happen before...not sure if related:
f69a2c5c302732bcc9e86e2570f2b208

**Comment by RecursiveVision** [comment]
@LoneGazebo Any ideas?

**Comment by LoneGazebo** [comment]
I just fixed it, merge to master (it was the fireplace folder that was OOS).

**Comment by RecursiveVision** [comment]
I'll merge in your changes and push.

**Comment by RecursiveVision** [comment]
@LoneGazebo Done! Ready to merge whenever you're ready (seems I introduced a tiny merge error, but should be easy to fix).

**Comment by RecursiveVision** [comment]
Hmm, okay. I'm gonna redo this pull request. :)

**Pull request closed without merging**
