### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by HeathcliffWarriors**
Whoops, forgot to replace some checks :)

### CODE REVIEW

**Comment by LoneGazebo** [comment]
@heathcliffwarriors I'm getting endless loops on trying to settle cities on this...

**Comment by LoneGazebo** [comment]
not every time, though. weird.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo With this pull request or the previous one?

**Comment by LoneGazebo** [comment]
nevermind, it isn't you, it's @ilteroi's code. Bad while loop.

**Comment by LoneGazebo** [comment]
sorry!

**Comment by HeathcliffWarriors** [comment]
No problem :)

**Pull request merged**
