### PR TITLE
RSI Diplomacy Rewrite Beta

### PR DESCRIPTION
**Pull request by RecursiveVision**
(Take 2!)

At long last, my changes are ready to be pushed. :)

**Notes**
This branch contains all of the changes from HungryForFood, pineappledan, Mileslewis and ilteroi, as well as my own changes to diplomacy and the files that Gazebo pushed to the repository.

**Deleted files/folder:** The PNM MODS DB/SMART folder and the files in it were deleted (see explanation below).

**Breaks savegames! (duh)**

My rework for the diplomacy AI memory system and my rewrite of many functions is included in this pull request.

I deleted a lot of the useless options from the database and DLL - I've never heard of any player disabling AI improvements or bugfixes, so we may as well have actually useful options there, and this removes hundreds of lines of useless #else'd out code. All of the changes from these bugfixes/improvements were preserved, of course - I simply removed the defines because these options are useless. The database should be saner/cleaner now!

Changelog (minus a few recent additions) was posted here: https://forums.civfanatics.com/threads/new-official-version-december-1st-12-1.665131/page-23#post-15991582

Recent additions:
- Additional modder requests from HungryForFood
- Fixed Roman Forum and Summer Palace not having a MaxStartEra
- Diplo debug mode in DiploAIOptions.sql now enables Intimate knowledge of all civs' World Congress desires (also enabled this for teammates, because it wasn't for some reason)
- Enabled war/peace/vassalage/Wonder construction notifications for Observers, and fixed the AI acting hostile to them
- Improvements to city liberation logic
- More adjustments to AI aggression
- Bugfixes for my previous changes

There will likely be some issues/bugs with my changes, but once they are ironed out I'm sure this will be a big improvement to AI behavior. I've fixed all the obvious bugs/problems I could find, and I've noticed the improved memory system for diplomacy seems to work a lot more reliably in terms of storing data consistently.

### CODE REVIEW

**Comment by RecursiveVision** [comment]
@LoneGazebo EnemyUnitPanel.lua files are still in the 43 Civ CP (EUI and no EUI) and normal NoEUI compatibility files. I've deleted these on this pull request (along with 2 other files and 1 folder; see above). 

Make sure these are synced with your local repository/etc. so there are no merge errors! :)

**Comment by RecursiveVision** [comment]
@LoneGazebo Deleted an additional two folders: PNM Mods DB > DIPLO and CONFIG folders, and the three contained files. 

Moved the changes to CoreDefines.sql and CoreChanges.xml for easier organization.

**Comment by LoneGazebo** [comment]
@RecursiveVision What's the status on this? Every time I go to merge I see that there are some beta quirks you're working on. What's it look like now? Trying to dive back into this is like trying to dive through a pinhole. :)

**Comment by RecursiveVision** [comment]
@LoneGazebo Fair enough haha. I'll get back to you shortly on that!

**Pull request closed without merging**
