### PR TITLE
C4DF Beta 3/11

### PR DESCRIPTION
**Pull request by mwhiter**
Merge instructions:

1) Civilization IV Diplomatic Features - CBP:
  a) Please add one InGameUIAddin for VassalOverview.lua, not two. Having two causes the double VO issue.
  b) Please import vassal80.dds and vassal80hl.dds into VFS!

Other notes:

I would ignore merging my .dll file, not sure why I'm commiting those.

Forum markup:

```
[B]General[/B]
[LIST]
[*]Updated civilopedia with new text for Vassalage
[*]New notification: Vassal is ready to be liberated.
[*]Moved .dds files for C4DF into C4DF - CP and C4DF - CBP folders, outside of the compatibility files.
[/LIST]

[B]Bug Fixes[/B]
[LIST]
[*]C4DF - CBP: Palace now has "VassalLevyEra" so masters should receive their era levies
[*]C4DF - CBP: Removed non-English texts (out of date, and were not removed in the last update)
[*]EUI: Vassal Overview should now correctly update on "Espionage dirty" (which also triggers when you change taxes)
[*]EUI: Fixed issue where old DiscussionDialog logic was not changed to the new (bug-free) logic
[*]EUI: Fixed bad tooltip display for Liberation trade option for CPU
[*]C4DF - CP: Fixed issue where Vassalage civilopedia entries didn't appear correctly.
[*]Fixed erroneous tooltip in Vassal Overview which stated that capitulated vassals count toward a Domination victory - this is a planned feature, but not an addition yet, so it should not display this.
[*]C4DF - CBP: Fixed major issue where capitulated vassals did not actually capitulated - this is a result of Peace Treaty deals not being counted with the correct Peace Treaty Type in DealClasses.cpp
[/LIST]
```

### CODE REVIEW

**Comment by LoneGazebo** [comment]
I don't have the modinfo file for C4DF - I've been manually editing it by hand all this time. :)
If you can upload the fixed modinfo file I'll include it.

**Comment by mwhiter** [comment]
Is that what you've been doing? Oh no, that won't be good.

I don't have one either...at least, one for C4DF CBP....

When I finish my standalone version, this will be sorted out and we'll both have what we need. But for now, I recommend continuing with this approach until my new release.

Add the following lines (taken from my dev .modinfo I created today)

<File md5="893FDC9F84ED2F09D4A7AEC2F2A4AFA8" import="1">LUA/VassalageOverview.lua</File>
    <File md5="30BA62E79F70C9FFDC0236C4ACE9AEC0" import="1">LUA/VassalageOverview.xml</File>
<File md5="E9029C9E9851D1E0138D792ED5F5A471" import="1">Images/vassal80.dds</File>
    <File md5="8050930951C51832D14A659C7DD22C3F" import="1">Images/vassal80hl.dds</File>

<EntryPoint type="InGameUIAddin" file="LUA/VassalageOverview.lua">
      <Name>Vassalage Overview</Name>
      <Description>Vassalage Overview</Description>
</EntryPoint>

Also a note: if for some reason EUI and Non-EUI have C4DF VO and .dds files...remove them. Although I should have done that in this commit.

**Comment by LoneGazebo** [comment]
C4DF CBP is the download copy of your mod from civfanatics from waaaay back in the day. I haven't needed to add anything to it, so it hasn't been an issue.

**Comment by LoneGazebo** [comment]
It shouldn't matter where the VO and DDS files are (C4DF, EUI, No-EUI, etc.) for this next beta. I fixed the uiaddin thing (not sure why it duplicated), and if the other problem was a DLL one, we're good to I imagine.

**Comment by mwhiter** [comment]
Right. Well, we'll change that, the copy of C4DF that will be maintained will be hosted on my github here:

https://github.com/mwhiter/C4DF-Standalone

Which will be updated sometime next week probably...when I'm done whipping up code for CPP.

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by mwhiter** [comment]
was this pull request satisfied? can we close it?

**Comment by LoneGazebo** [comment]
Yeah, we can close it.

**Pull request closed without merging**
