### PR TITLE
Franklin Roosevelt 30/5/2018

### PR DESCRIPTION
**Pull request by HungryForFood**
Not save game compatible.

## IsCapitalOnly
- Added IsCapitalOnly column to Traits. Currently only affects Trait_YieldChangesPerImprovementBuilt.

@Hokath Do you want to experiment with the changes now? I can send you a compiled DLL.

### CODE REVIEW

**Comment by Hokath** [comment]
That would be very kind!

Sent from Yahoo Mail on Android 
 
  On Wed, 30 May 2018 at 15:31, JJ<notifications@github.com> wrote:   
Not save game compatible.

IsCapitalOnly
   
   - Added IsCapitalOnly column to Traits. Currently only affects Trait_YieldChangesPerImprovementBuilt.

@Hokath Do you want to experiment with the changes now? I can send you a compiled DLL.

You can view, comment on, or merge this pull request online at:

  https://github.com/LoneGazebo/Community-Patch-DLL/pull/4443

Commit Summary
   
   - Roosevelt changes 30/5/2018

File Changes
   
   -  M Community Patch/Core Files/Core Tables/CoreTableEntries.sql (5) 
   -  M CvGameCoreDLL_Expansion2/CvCity.cpp (29) 
   -  M CvGameCoreDLL_Expansion2/CvTraitClasses.cpp (14) 
   -  M CvGameCoreDLL_Expansion2/CvTraitClasses.h (7) 

Patch Links:
   
   - https://github.com/LoneGazebo/Community-Patch-DLL/pull/4443.patch
   - https://github.com/LoneGazebo/Community-Patch-DLL/pull/4443.diff

**Comment by HungryForFood** [comment]
@Hokath 

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2057467/CvGameCore_Expansion2.zip)

**Comment by Hokath** [comment]
[289017.562] In Query - insert into Traits('Type', 'Description', 'ShortDescription', 'FreeCapitalBuilding', 'IsOddEraScaler', 'IsCapitalOnly') values (?, ?, ?, ?, ?, ?);

It no work :(

**Comment by HungryForFood** [comment]
@Hokath You have problems getting it to work? Github sent me a notification, but I don't see the actual message here.

If you do, you probably didn't copy the latest Community Patch/Core Files/Core Tables/CoreTableEntries.sql from Github into your mod folder.

**Comment by Hokath** [comment]
Yeah I realised immediately after posting 😀
On the point of the design, how did you find the per-city balance with roosevelt? It seemed to me that for global yields (for you culture, for me science) require themselves to be balanced around having many cities (especially puppets) and so are pretty naff for smaller empires. Hence the looking for capital-only yields. What is your feeling?Sent from Yahoo Mail on Android 
 
  On Fri, 1 Jun 2018 at 6:43, JJ<notifications@github.com> wrote:   
@Hokath You have problems getting it to work? Github sent me a notification, but I don't see the actual message here.

If you do, you probably didn't copy the latest Community Patch/Core Files/Core Tables/CoreTableEntries.sql from Github into your mod folder.

**Comment by HungryForFood** [comment]
At the very least they don't seem overpowered. In that mod, you really only feel the culture since that is triggered by three different improvements. The other yields, not so much, but I left it in for flavour.

The culture seems to be on par or slightly lower than the Inspiration belief, until late game when Inspiration caps out. However, Roosevelt's UA also boosts GP production, leading to more GPTI and thus more yields. On the other hand, you want to bulb GPs late game, so that acts sort of like a cap.

**Comment by Hokath** [comment]
I'm looking at Holy Sites, so there is also a soft cap related to faith/GP. It tends to ramp up quite quickly from not very many to a stable-ish number like 7 or 8 in the mid-game. So if each gives a base +1 science then +14 science per city seemed like quite a lot at medieval/renaissance c.f. korea for instance. If there is no era scaling then it becomes worthless later in the game because of the soft cap. So next round I'm going to try +3 base only in the Capital.

Anyway thanks so much for fixing that! :D

**Pull request merged**
