### PR TITLE
Ole

### PR DESCRIPTION
**Pull request by RecursiveVision**

### CODE REVIEW

**Comment by LoneGazebo** [comment]
I'll have to do a forced merge on this.

**Comment by RecursiveVision** [comment]
@LoneGazebo What does a forced merge entail? Do I need to worry about my edits from last version being undone? I notice they're not all present in the ole branch right now.

**Comment by RecursiveVision** [comment]
I pushed the missing files from #6706 to ole.

**Comment by RecursiveVision** [comment]
I'm going to redo this today to make sure everything's included and merged properly.

**Pull request closed without merging**
