### PR TITLE
Fixes for #3807 #3810

### PR DESCRIPTION
**Pull request by Infixo**
#3807 #3810

### CODE REVIEW

**Comment by Infixo** [comment]
@ilteroi How can I make this Stackwalker thing work? I mean, I can't compile the DLL without STACKWALKER in preprocessor.

**Comment by ilteroi** [comment]
the source for the stackwalker is present in CvGameCoreDLL_Expansion2\stackwalker ... which project file are you using? the flag should be defined in the project settings (c++/preprocessor)

anyway, i haven't used it for a while, i'm fine with disabling it ...

**Comment by Infixo** [comment]
Master. When I downloaded it for the first time, I couldn't compile the project. I had to define STACKWALKER in preprocessor. If I remove it, I get errors about pStackWalker not being defined.

**Comment by Infixo** [comment]
I get error from this line: gStackWalker.ShowCallstack(); in CvAStar.cpp and CvRandom.cpp.

**Pull request closed without merging**
