### PR TITLE
Amidoingthisrite

### PR DESCRIPTION
**Pull request by iskaandismet**
Files that should have been altered:
-CustomMods.cpp/.h
-CvReligionClasses.cpp/.h

### CODE REVIEW

**Comment by iskaandismet** [comment]
My repo is out of date? Can't seem to resolve the conflicts. Didn't intend to remove anything, should only have made additions to files listed.

**Comment by LoneGazebo** [comment]
Yes, you need to merge your full repo then make changes.

**Comment by iskaandismet** [comment]
You can, of course, tell me to google instead of answering, but I don't suppose you could save me some time and explain how to do that with Toirtoisegit?

**Comment by LoneGazebo** [comment]
Your best bet would be to download master, replace your existing repo on your local machine, and _then_ make your changes.

**Comment by LoneGazebo** [comment]
You can even use a program like Winmerge to compare your files to master and only edit what you want.

**Comment by supermerill** [comment]
in tortoisegit: go to git status
clic on "master" on top left and then on "ref"
select all labels (at least your head and the two remote/X/head)
right-clic on the last commit from gazebo (should be remote/LoneGazebo/head) and clic merge
then it will cry as it's unmergeable. Clic on "resolve"
then you have a list of files to merge manually, double-clic on one to edit.
after everything is in "resolved" state, do a commit.
finish! now you can test, debug, commit and push.

**Pull request closed without merging**
